### ISSUE TITLE
config-nell.json

### ISSUE THREAD

**Issue by David-Lee-1990** [THUDM/CogKR#1]
Hi, thanks for sharing your code for your beautiful model of graph-shaping reasoning. I just try to run a test on nell-one data. And follow your guidence:
 1.   
`python src/main.py  --directory datasets/NELL/ --gpu 0 --config configs/config-nell.json --load_embed DistMult --comment nell`

2. 
`python src/main.py --inference --directory datasets/NELL/ --gpu 3 --config configs/config-nell.json --load_embed DistMult --load_state ./datasets/NELL/log/11-26-13-nell/best.state`

and I get the following results which seems not at the same scale as your paper shows.
![image](https://user-images.githubusercontent.com/29653610/69696871-f7f46680-111b-11ea-8dda-cba765c51255.png)

So, is there any other parameters to add or the config-nell.json is not the best hyparameters?

**Comment by duzx16** [comment]
Sorry for the late response. config-nell.json is the hyperparameter we used in our experiments. I think the problem is that the parameters haven't converged yet. You need about 50k - 100k steps to achieve the optimal performance, while the evaluation is conducted every 5k steps. Hopefully this can address your problem.
